"""
Type stub for privy.utils - upstream ships none.
"""

def base64_to_bytes(s: str | bytes) -> bytes: ...
def bytes_to_base64(s: bytes) -> str: ...
def ensure_bytes(s: str | bytes) -> bytes: ...
def ensure_unicode(s: str | bytes) -> str: ...

